groups:

- name: all
  jobs:
  - bootstrap-terraform-state
  - wipe-env
  - create-infrastructure
  - config-opsman-auth
  - config-director
  - deploy-director
  - upload-ert
  - configure-ert
  - deploy-ert

- name: iaas
  jobs:
  - create-infrastructure
  - config-opsman-auth
  - config-director
  - deploy-director

- name: ert
  jobs:
  - upload-ert
  - configure-ert
  - deploy-ert

resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: czero/azure-blobstore-resource

- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: terraform-state
  type: azure-blobstore
  source:
    storage_account_name: {{terraform_azure_account_name}}
    storage_account_key: {{terraform_azure_access_key}}
    container: {{terraform_statefile_container}}
    versioned_file: terraform.tfstate

- name: pcf-pipelines
  type: git
  source:
    uri: https://github.com/pivotal-cf/pcf-pipelines.git
    branch: 148603651-azure-pipeline

- name: tool-om
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: {{githubtoken}}

- name: pivnet-opsmgr
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: ops-manager
    product_version: {{opsman_major_minor_version}}
    sort_by: semver

- name: pivnet-elastic-runtime
  type: pivnet
  check_every: 4h
  source:
    api_token: {{pcf_pivnet_token}}
    product_slug: elastic-runtime
    product_version: {{ert_major_minor_version}}
    sort_by: semver

jobs:
####################################
## Job - Boostrap Terraform State ##
####################################
- name: bootstrap-terraform-state
  serial_groups: [terraform]
  plan:
  - get: pcf-pipelines
  - task: create-terraform-state
    params:
      AZURE_STORAGE_ACCOUNT: {{terraform_azure_account_name}}
      AZURE_STORAGE_KEY: {{terraform_azure_access_key}}
      CONTAINER: {{terraform_statefile_container}}
    file: pcf-pipelines/install-pcf/azure/tasks/create-initial-terraform-state/task.yml

#####################
## Job - Wipe Env  ##
#####################
- name: wipe-env
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  ensure:
    put: terraform-state
    params:
      file: terraform-state-output/terraform.tfstate
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: false
    - get: terraform-state

  - task: wipe-env
    file: pcf-pipelines/install-pcf/azure/tasks/wipe-env/task.yml
    params:
      ARG_WIPE: {{arg_wipe}}
      AZURE_PCF_TERRAFORM_TEMPLATE: {{azure_pcf_terraform_template}}
      AZURE_SUBSCRIPTION_ID: {{azure_subscription_id}}
      AZURE_TENANT_ID: {{azure_tenant_id}}
      AZURE_SERVICE_PRINCIPAL_ID: {{azure_service_principal_id}}
      AZURE_SERVICE_PRINCIPAL_PASSWORD: {{azure_service_principal_password}}
      AZURE_REGION: {{azure_region}}
      AZURE_TERRAFORM_PREFIX: {{azure_terraform_prefix}}
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}

#################################
## Job - Create Infrastructure ##
#################################
- name: create-infrastructure
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  ensure:
    put: terraform-state
    params:
      file: terraform-state-output/terraform.tfstate
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: false
    - get: terraform-state
    - get: pivnet-opsmgr
      trigger: false
      params:
        globs:
        - "*Azure.yml"

  - task: upload-opsman
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: pivnet-opsmgr
      outputs:
        - name: opsman-metadata
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/upload-opsman.sh

  - task: create-infrastructure
    file: pcf-pipelines/install-pcf/azure/tasks/create-infrastructure/task.yml
    params:
      AZURE_PCF_TERRAFORM_TEMPLATE: {{azure_pcf_terraform_template}}
      AZURE_SUBSCRIPTION_ID: {{azure_subscription_id}}
      AZURE_TENANT_ID: {{azure_tenant_id}}
      AZURE_SERVICE_PRINCIPAL_ID: {{azure_service_principal_id}}
      AZURE_SERVICE_PRINCIPAL_PASSWORD: {{azure_service_principal_password}}
      AZURE_REGION: {{azure_region}}
      AZURE_TERRAFORM_PREFIX: {{azure_terraform_prefix}}
      AZURE_VM_ADMIN: {{azure_vm_admin}}
      AZURE_VM_PASSWORD: {{azure_vm_password}}
      PCF_ERT_DOMAIN: {{pcf_ert_domain}}
      PCF_OPSMAN_ADMIN: {{pcf_opsman_admin_username}}
      PCF_OPSMAN_ADMIN_PASSWORD: {{pcf_opsman_admin_password}}
      PCF_SSH_KEY_PUB: {{pcf_ssh_key_pub}}
      AZURE_ACCOUNT_NAME: {{azure_account_name}}
      AZURE_BUILDPACKS_CONTAINER: {{azure_buildpacks_container}}
      AZURE_DROPLETS_CONTAINER: {{azure_droplets_container}}
      AZURE_PACKAGES_CONTAINER: {{azure_packages_container}}
      AZURE_RESOURCES_CONTAINER: {{azure_resources_container}}
      AZURE_TERRAFORM_PREFIX: {{azure_terraform_prefix}}
      AZURE_TERRAFORM_VNET_CIDR: {{azure_terraform_vnet_cidr}}
      AZURE_TERRAFORM_SUBNET_INFRA_CIDR: {{azure_terraform_subnet_infra_cidr}}
      AZURE_TERRAFORM_SUBNET_ERT_CIDR: {{azure_terraform_subnet_ert_cidr}}
      AZURE_TERRAFORM_SUBNET_SERVICES1_CIDR: {{azure_terraform_subnet_services1_cidr}}
      AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_CIDR: {{azure_terraform_subnet_dynamic_services_cidr}}

##############################
## Job - Config OpsMan Auth ##
##############################
- name: config-opsman-auth
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [create-infrastructure]
    - get: tool-om
      params:
        globs:
        - "om-linux"

  - task: config-opsman
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: tool-om
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/config-opsman.sh
      params:
        PCF_ERT_DOMAIN: {{pcf_ert_domain}}
        PCF_OPSMAN_ADMIN: {{pcf_opsman_admin_username}}
        PCF_OPSMAN_ADMIN_PASSWORD: {{pcf_opsman_admin_password}}

###########################
## Job - Config-Director ##
###########################
- name: config-director
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [config-opsman-auth]
    - get: tool-om
      params:
        globs:
        - "om-linux"

  - task: config-director
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: tool-om
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/config-director.sh
      params:
        OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
        PCF_OPSMAN_ADMIN: {{pcf_opsman_admin_username}}
        PCF_OPSMAN_ADMIN_PASSWORD: {{pcf_opsman_admin_password}}
        AZURE_PCF_TERRAFORM_TEMPLATE: {{azure_pcf_terraform_template}}
        AZURE_SUBSCRIPTION_ID: {{azure_subscription_id}}
        AZURE_TENANT_ID: {{azure_tenant_id}}
        AZURE_SERVICE_PRINCIPAL_ID: {{azure_service_principal_id}}
        AZURE_SERVICE_PRINCIPAL_PASSWORD: {{azure_service_principal_password}}
        AZURE_TERRAFORM_PREFIX: {{azure_terraform_prefix}}
        AZURE_TERRAFORM_SUBNET_INFRA_CIDR: {{azure_terraform_subnet_infra_cidr}}
        AZURE_TERRAFORM_SUBNET_INFRA_RESERVED: {{azure_terraform_subnet_infra_reserved}}
        AZURE_TERRAFORM_SUBNET_INFRA_DNS: {{azure_terraform_subnet_infra_dns}}
        AZURE_TERRAFORM_SUBNET_INFRA_GATEWAY: {{azure_terraform_subnet_infra_gateway}}
        AZURE_TERRAFORM_SUBNET_ERT_CIDR: {{azure_terraform_subnet_ert_cidr}}
        AZURE_TERRAFORM_SUBNET_ERT_RESERVED: {{azure_terraform_subnet_ert_reserved}}
        AZURE_TERRAFORM_SUBNET_ERT_DNS: {{azure_terraform_subnet_ert_dns}}
        AZURE_TERRAFORM_SUBNET_ERT_GATEWAY: {{azure_terraform_subnet_ert_gateway}}
        AZURE_TERRAFORM_SUBNET_SERVICES1_CIDR: {{azure_terraform_subnet_services1_cidr}}
        AZURE_TERRAFORM_SUBNET_SERVICES1_RESERVED: {{azure_terraform_subnet_services1_reserved}}
        AZURE_TERRAFORM_SUBNET_SERVICES1_DNS: {{azure_terraform_subnet_services1_dns}}
        AZURE_TERRAFORM_SUBNET_SERVICES1_GATEWAY: {{azure_terraform_subnet_services1_gateway}}
        AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_CIDR: {{azure_terraform_subnet_dynamic_services_cidr}}
        AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_RESERVED: {{azure_terraform_subnet_dynamic_services_reserved}}
        AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_DNS: {{azure_terraform_subnet_dynamic_services_dns}}
        AZURE_TERRAFORM_SUBNET_DYNAMIC_SERVICES_GATEWAY: {{azure_terraform_subnet_dynamic_services_gateway}}
        PCF_SSH_KEY_PUB: {{pcf_ssh_key_pub}}
        PCF_SSH_KEY_PRIV: {{pcf_ssh_key_priv}}
        TRUSTED_CERTIFICATES: {{trusted_certificates}}

###########################
## Job - Deploy-Director ##
###########################
- name: deploy-director
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [config-director]
    - get: pivnet-opsmgr
      trigger: true
      params: {globs: []}
    - get: tool-om
      params:
        globs:
        - "om-linux"
    - get: pivnet-elastic-runtime
      trigger: false
      params:
        globs:
        - "*pivotal"

  - task: deploy-director
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: czero/cflinuxfs2
      inputs:
        - name: pcf-pipelines
        - name: tool-om
      run:
        path: pcf-pipelines/install-pcf/azure/tasks/iaas/deploy-director.sh
      params:
        OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
        PCF_OPSMAN_ADMIN: {{pcf_opsman_admin_username}}
        PCF_OPSMAN_ADMIN_PASSWORD: {{pcf_opsman_admin_password}}

###########################
## Job - Upload ERT      ##
###########################
- name: upload-ert
  serial_groups: [opsman]
  plan:
  - aggregate:
    - get: pcf-pipelines
    - get: pivnet-opsmgr
      passed: [deploy-director]
      trigger: true
      params: {globs: []}
    - get: pivnet-product
      resource: pivnet-elastic-runtime
      params:
        globs:
        - "*pivotal"

  - task: upload-tile
    file: pcf-pipelines/tasks/upload-product-and-stemcell/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPS_MGR_USR: {{pcf_opsman_admin_username}}
      OPS_MGR_PWD: {{pcf_opsman_admin_password}}
      PIVNET_API_TOKEN: {{pcf_pivnet_token}}
      IAAS: "azure"
      NO_PROXY: ""
      OM_IP: ""

  - task: stage-tile
    file: pcf-pipelines/tasks/stage-product/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
      PRODUCT_NAME: cf

###########################
## Job - Configure ERT   ##
###########################
- name: configure-ert
  serial: true
  max_in_flight: 1
  serial_groups: [full]
  plan:
  - aggregate:
    - get: pcf-pipelines
      passed: [upload-ert]
      trigger: true
    - get: terraform-state
    - get: tool-om
      params:
        globs:
        - "om-linux"

  - task: configure-ert
    file: pcf-pipelines/tasks/configure-ert/task.yml
    params:
      pcf_iaas: {{pcf_iaas}}
      pcf_ert_domain: {{pcf_ert_domain}}
      OPS_MGR_USR: {{pcf_opsman_admin_username}}
      OPS_MGR_PWD: {{pcf_opsman_admin_password}}
      pcf_ert_ssl_cert: {{pcf_ert_ssl_cert}}
      pcf_ert_ssl_key: {{pcf_ert_ssl_key}}
      terraform_prefix: {{azure_terraform_prefix}}
      pcf_ert_saml_cert: {{pcf_ert_saml_cert}}
      pcf_ert_saml_key: {{pcf_ert_saml_key}}
      pcf_ert_networking_pointofentry: {{pcf_ert_networking_pointofentry}}
      azure_access_key: {{azure_access_key}}
      azure_account_name: {{azure_account_name}}
      azure_buildpacks_container: {{azure_buildpacks_container}}
      azure_droplets_container: {{azure_droplets_container}}
      azure_packages_container: {{azure_packages_container}}
      azure_resources_container: {{azure_resources_container}}
      mysql_monitor_recipient_email: {{mysql_monitor_recipient_email}}
      MYSQL_BACKUPS: {{mysql_backups}}
      MYSQL_BACKUPS_SCP_SERVER: {{mysql_backups_scp_server}}
      MYSQL_BACKUPS_SCP_PORT: {{mysql_backups_scp_port}}
      MYSQL_BACKUPS_SCP_USER: {{mysql_backups_scp_user}}
      MYSQL_BACKUPS_SCP_KEY: {{mysql_backups_scp_key}}
      MYSQL_BACKUPS_SCP_DESTINATION: {{mysql_backups_scp_destination}}
      MYSQL_BACKUPS_SCP_CRON_SCHEDULE: {{mysql_backups_scp_cron_schedule}}
      MYSQL_BACKUPS_S3_ENDPOINT_URL: {{mysql_backups_s3_endpoint_url}}
      MYSQL_BACKUPS_S3_BUCKET_NAME: {{mysql_backups_s3_bucket_name}}
      MYSQL_BACKUPS_S3_BUCKET_PATH: {{mysql_backups_s3_bucket_path}}
      MYSQL_BACKUPS_S3_ACCESS_KEY_ID: {{mysql_backups_s3_access_key_id}}
      MYSQL_BACKUPS_S3_SECRET_ACCESS_KEY: {{mysql_backups_s3_secret_access_key}}
      MYSQL_BACKUPS_S3_CRON_SCHEDULE: {{mysql_backups_s3_cron_schedule}}
      db_diego_username: {{db_diego_username}}
      db_diego_password: {{db_diego_password}}
      db_notifications_username: {{db_notifications_username}}
      db_notifications_password: {{db_notifications_password}}
      db_autoscale_username: {{db_autoscale_username}}
      db_autoscale_password: {{db_autoscale_password}}
      db_uaa_username: {{db_uaa_username}}
      db_uaa_password: {{db_uaa_password}}
      db_app_usage_service_username: {{db_app_usage_service_username}}
      db_app_usage_service_password: {{db_app_usage_service_password}}
      db_ccdb_username: {{db_ccdb_username}}
      db_ccdb_password: {{db_ccdb_password}}
      db_routing_username: {{db_routing_username}}
      db_routing_password: {{db_routing_password}}
      db_accountdb_username: {{db_accountdb_username}}
      db_accountdb_password: {{db_accountdb_password}}
      db_networkpolicyserverdb_username: {{db_networkpolicyserverdb_username}}
      db_networkpolicyserverdb_password: {{db_networkpolicyserverdb_password}}
      db_nfsvolumedb_username: {{db_nfsvolumedb_username}}
      db_nfsvolumedb_password: {{db_nfsvolumedb_password}}
      db_silk_username: {{db_silk_username}}
      db_silk_password: {{db_silk_password}}
      db_locket_username: {{db_locket_username}}
      db_locket_password: {{db_locket_password}}
      pcf_az_1:
      pcf_az_2:
      pcf_az_3:
      gcp_storage_access_key:
      gcp_storage_secret_key:
      S3_ENDPOINT:

###########################
## Job - Deploy    ERT   ##
###########################
- name: deploy-ert
  serial: true
  max_in_flight: 1
  serial_groups: [full]

  plan:
  - aggregate:
    - get: pcf-pipelines
      trigger: true
      passed: [configure-ert]
    - get: tool-om
      params:
        globs:
        - "om-linux"

  - task: deploy-ert
    file: pcf-pipelines/tasks/apply-changes/task.yml
    params:
      OPSMAN_DOMAIN_OR_IP_ADDRESS: {{opsman_domain_or_ip_address}}
      OPSMAN_USERNAME: {{pcf_opsman_admin_username}}
      OPSMAN_PASSWORD: {{pcf_opsman_admin_password}}
